- Artifical Intelligence 1_Building Software That Recognizes You/face-api/train-face-api.md
Correct the retrieving a key to now retrieve the face-api key previously the code was retrieving the customvision key
> Update to Retrieving a Key

- Artifical Intelligence 1_Building Software That Recognizes You/README.md
- Artifical Intelligence 1_Building Software That Recognizes You/computer-vision-translator/computer-vision.md
- Artifical Intelligence 1_Building Software That Recognizes You/computer-vision-translator/create-computer-vision-keys.md
- Artifical Intelligence 1_Building Software That Recognizes You/computer-vision-translator/deploy.md
- Artifical Intelligence 1_Building Software That Recognizes You/computer-vision-translator/explore-app-py.md
- Artifical Intelligence 1_Building Software That Recognizes You/computer-vision-translator/translator.md
- Artifical Intelligence 1_Building Software That Recognizes You/face-api/train-face-api.md
- Artifical Intelligence 1_Building Software That Recognizes You/overview.md
- Artifical Intelligence 1_Building Software That Recognizes You/setup.md
- Added information about creating an account
- Removed `en-us` from content
> Signup and globalization

- Artifical Intelligence 1_Building Software That Recognizes You/face-api/detect-face-api.md
Looks like the code in detect_people was modified to no longer have the code to fetch names in a separate helper method. But the instructions seem to have a section that looks like it is leftover from a previous version of the code
> Unncessary Code explanation

- AI_1/computer-vision-translator/create-computer-vision-keys.md
- AI_1/computer-vision-translator/deploy.md
- AI_1/face-api/deploy.md
- AI_1/solution-site/.gitignore
- AI_1/solution-site/app.py
- AI_1/starter-site/.gitignore
- AI_1/starting-site.md
> Clarified deployment

- AI_1/intro-python.md
> Small typo fix

- AI_1/setup.md
Added instructions on how to perform the install using Chocolatey on Windows, Homebrew on macOS, and apt-get & Snap on Ubuntu.
> Added quick install guides

- AI_1/computer-vision-translator/computer-vision.md
While working through this code, I found my debugging statements were triggering errors. Once I removed this catch-all except block, I was able to trivially fix my mistake. I'd recommend to remove this for easier troubleshooting -- this would also likely help with credential issues.
> Allow exceptions to bubble up

- Data_Science_2/Full_Day/2-MachineLearningModels-Reference.ipynb
Fixes #39 
Update the path to read the CSV files from the Data directory.
> Update path to read csv files

- AI_1/solution-site/templates/translate.html
- AI_1/starter-site/templates/translate.html
> Swap values for simplified and traditional Chinese

- Online/Async_JavaScript.md
Add doc for async JS livestream. Includes information about:
- async programming in JS
- callbacks
- promises
- async/await
> Add doc on async javascript

- Data_Science_1/LearnModules/1-Python.ipynb
I just ran the cells in the Python notebook
> Ran all of the cells

- Blockchain_1/.gitignore
- Blockchain_1/Completed_Solutions/contracts/Banker.sol
- Blockchain_1/Part_2_Solidity_Introduction/Create_SimpleStorage_contract/README.md
- Blockchain_1/Part_5_Building_Smart_Contracts_For_Blockopoly/Building_Blockopoly/BankerContract/contracts/Banker.sol
- Add a .gitignore for node_modules/
- Update some instructions in README
- Some code updates for the Banker contract
> Blockchain_1 changes

- Online/Blockchain/Blockchain-fundamentals/README.md
- Online/Blockchain/Blockchain_Fundamentals/README.md
Add the instructions to complete the demo for the blockchain foundations stream
> Add demo for blockchain stream

- .github/ISSUE_TEMPLATE/digital-event-tracking-issue.md
- .github/ISSUE_TEMPLATE/in-person-event-tracking-issue
- .github/ISSUE_TEMPLATE/new-content.md
First draft of these issue templates.
> Update issue templates

- In-Person Events/README.md
- Online/README.md
This README will track all content for the digital learning experiences.
> Adding a README to track the learning content

- online-event-resources/data-science-and-machine-learning/automated-machine-learning/readme.md
adding video demos to readme ... in case of slow internet issues
> add video demos to readme

- online-event-resources/web-development/rust101/src/main_with_object.rs
While delivering a Reactor on rust, I put together an alternative implementation of the exercise using `struct` and methods. It demonstrates some more of the features of the rust language.
I figured I'd share it back upstream in case you would like to include it, no worries if not. 😄
> Add implementation demonstrating use of Struct and methods for rust.

- cloud-app-dev/introduccion-azure-functions/README.md
- cloud-app-dev/introduccion-azure-functions/desarollo/README.md
- cloud-app-dev/introduccion-azure-functions/encadenamiento/README.md
- cloud-app-dev/introduccion-azure-functions/signalr/README.md
Adding content for NYC Spanish Azure Functions January sessions.
> Adding jan nyc series

- devops-devtools/intro-linux-en-azure/README.md
- devops-devtools/intro-linux-en-azure/intro-a-aks/README.md
- devops-devtools/intro-linux-en-azure/intro-a-bash/README.md
- devops-devtools/intro-linux-en-azure/intro-a-docker/README.md
- devops-devtools/intro-linux-en-azure/intro-a-terraform/README.md
- devops-devtools/intro-linux-on-azure/README.md
- devops-devtools/intro-linux-on-azure/intro-to-aks/README.md
- devops-devtools/intro-linux-on-azure/intro-to-bash/README.md
- devops-devtools/intro-linux-on-azure/intro-to-docker-azure/README.md
- devops-devtools/intro-linux-on-azure/intro-to-iac-terraform/README.md
I added folders in the Devops category for series:
- Linux on azure
- Linux en Azure
Also added individual sessions and main readme with TOC of each session.
> Nyc adding feb series

- cloud-app-dev/serverless-en-febrero/README.md
- cloud-app-dev/serverless-on-january/README.md
- low-nocode/LC-NC-February-Eng/readme.md
- low-nocode/LC-NC-February-Spa/readme.md
- serverless in english
- serverless in spanish
- lowcode-nocode  in english
- lowcode-nocode in spanish
> Added February and March series for serverless and lowcode - nocode

- cloud-app-dev/serverless-en-febrero/README.md
- cloud-app-dev/serverless-on-january/README.md
- low-nocode/LC-NC-February-Eng/readme.md
- low-nocode/LC-NC-February-Spa/readme.md
adding small desc to each session
> adding format to session tables

- devops-devtools/intro-linux-on-azure/intro-to-bash/README.md
I added instructor notes to resources and updated the learn module link.
> Added resources link to Intro to bash session

- devops-devtools/intro-linux-en-azure/intro-a-bash/README.md
I added the learn module and instructor notes links to intro to bash Spanish session
> Added links to intro to bash spanish session

- low-nocode/low-nocode-developer-day.md
Changes:
1. Links updated for RSVP.
2. Added Speakers, Title & Livestream link.
3. Cloud Skills Challenge launched.
@madebygps can you review & merge if no changes.
> Low-code/ No-code developer day Updated

- low-nocode/low-nocode-developer-day.md
Low-code / No-code developer day repo update:
1. Monthly resource GitHub repo updated to align with Dev Marketing team.
2. Added some style to highlight repo & cloud skills challenge.
> Low-code / No-code developer day [monthly resource updated]

- devops-devtools/intro-linux-on-azure/intro-to-docker-azure/README.md
I added instructor notes link to the into to containers readme.
> Added link to intro-to-containers md

- devops-devtools/intro-linux-en-azure/intro-a-docker/README.md
Just Added instructor notes link to readme :)
> Added link to intro-a-docker md

- cloud-app-dev/30days-azuredev-challenge/README.md
> Update README.md in 30days azure challenge

- devops-devtools/intro-linux-on-azure/intro-to-aks/README.md
I added the instructor notes link to AKS session
> Added instructor notes link to aks session

- devops-devtools/intro-linux-en-azure/intro-a-aks/README.md
Added a link to my intro a aks readme
> Added links to readme

- cloud-app-dev/building-networks-azure/README.md
- cloud-app-dev/building-networks-azure/build-vnet-bicep/README.md
- cloud-app-dev/building-networks-azure/secure-azure-vnet/README.md
- cloud-app-dev/building-networks-azure/work-within-vnet/README.md
Creating md for April networking series.
> Added networking April series

- microsoft-student-developer-day/april-2022/README.md
Move hashtag #MSDDay to #MSDevDay!
> Updated hastag

- workshop-resources/data-science-and-machine-learning/Data_Science_1/loan-project/1-loan-activity.md
It was a broken link to a Google drive location. Fixed. Now pointing to the files in this repo.
> Fix data file links

- microsoft-student-developer-day/July-2022/README.md
Launching MSDevDay India second edition.
> Msdevday india

- microsoft-student-developer-day/October-2022/README.md
The session title was mentioned as "Introduction to GitHub & Azure", but the session is only about GitHub, thus it should be "Introduction to GitHub".
> Correction of Session Title

- coding-languages-frameworks/code-garden-advent-of-code-2022/day6-example.txt
- coding-languages-frameworks/code-garden-advent-of-code-2022/day6.py
- coding-languages-frameworks/code-garden-advent-of-code-2022/day7-example.txt
- coding-languages-frameworks/code-garden-advent-of-code-2022/day7.py
- coding-languages-frameworks/code-garden-advent-of-code-2022/day8.py
Co-authored-by: Jack Reichelt <jackreichelt@users.noreply.github.com>
> Advent of code garden ep 2 problems 6-8

- coding-languages-frameworks/code-garden-advent-of-code-2022/day10.py
- coding-languages-frameworks/code-garden-advent-of-code-2022/day11.py
- coding-languages-frameworks/code-garden-advent-of-code-2022/day12.py
- coding-languages-frameworks/code-garden-advent-of-code-2022/day13.py
- coding-languages-frameworks/code-garden-advent-of-code-2022/day9.py
Co-authored-by: Jack Reichelt <jackreichelt@users.noreply.github.com>
> In the Code Garden - Advent of Code Garden Episode 3
